import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col bg-black">
        <div
          aria-hidden
          className="fixed inset-0 -z-10"
          style={{
            backgroundImage: "url(/background/toronto-bg.jpg)",
            backgroundSize: "cover",
            backgroundPosition: "center",
            filter: "blur(14px) saturate(0.7)",
            transform: "scale(1.08)",
          }}
        />
        <div aria-hidden className="fixed inset-0 -z-10 bg-black/75" />
        {children}
      </body>
    </html>
  );
}
